### ISSUE TITLE
No sound on Wayland + pulseaudio

### ISSUE THREAD

**Issue by twitchyliquid64** [Anuken/Arc#133]
Everything works fine except sound. Heres console output:

```
[I] [Core] Initialized SDL v2.24.0
[E] Failed to initialize audio, disabling sound: arc.util.ArcRuntimeException: Other error
	at arc.audio.Soloud.init(Native Method)
	at arc.audio.Audio.initialize(Audio.java:41)
	at arc.audio.Audio.<init>(Audio.java:30)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:42)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

[I] [GL] Version: OpenGL 4.6.0 / AMD / AMD Radeon RX 590 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.78)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.4
[I] [RAM] Available: 7.8 GB
[I] [Mindustry] Version: 140.3
[I] Total time to load: 2014ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 26 community servers.
[I] Connecting to server: /165.232.137.170:6567
[I] Received world data: 146967 bytes.
```

I'm using the packaging here: https://github.com/NixOS/nixpkgs/pull/200743

**Comment by twitchyliquid64** [comment]
I think this is a package integration issue with nixOS at head.

I'll keep digging.

**Comment by chkno** [comment]
Probably fixed with https://github.com/NixOS/nixpkgs/pull/200743 ?

**Comment by chkno** [comment]
Yes, twitchyliquid64 [confirms](https://github.com/NixOS/nixpkgs/pull/200743#issuecomment-1322974662) that this is now fixed.
